services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    restart: unless-stopped

    ports:
      - "9000:9000"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/administrador/homelab-data/portainer:/data

    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.homelab`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  homelab:
    external: true
