services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma

    restart: unless-stopped

    ports:
      - "3001:3001"

    volumes:
      - /home/administrador/homelab-data/uptime-kuma:/app/data

    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.homelab`)"
      - "traefik.http.routers.uptime.entrypoints=web"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"

networks:
  homelab:
    external: true
