services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n

    restart: unless-stopped

    ports:
      - "${N8N_PORT}:5678"

    environment:
      - TZ=${TZ}
      - N8N_SECURE_COOKIE=${N8N_SECURE_COOKIE}

    volumes:
      - /home/administrador/homelab-data/n8n:/home/node/.n8n

    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.homelab`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

networks:
  homelab:
    external: true
