services:
  api:
    build: .
    container_name: api
    hostname: debian-server
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.homelab`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

networks:
  homelab:
    external: true
